import 'package:flutter/material.dart';

final Map<String, String> emotionImages = {
  'Happy': 'lib/assets/Happy.png',
  'Angry!': 'lib/assets/Angry.png',
  'Tired': 'lib/assets/NoMood.png',
  'Frustrated': 'lib/assets/Sad.png',
  'Awful': 'lib/assets/Awful.png',
  'In love': 'lib/assets/Enamorado.png',
  'Relaxed': 'lib/assets/Sleepy.jpg',
  'Excited': 'lib/assets/Party.png'
};
final colores = {
  'Happy': Color.fromARGB(255, 224, 197, 63),
  'Angry!': Color.fromARGB(255, 255, 58, 64),
  'Tired': Color.fromARGB(255, 117, 174, 174),
  'Frustrated': Color.fromARGB(255, 154, 178, 244),
  'Awful': Color.fromARGB(255, 72, 127, 255),
  'In love': Color.fromARGB(255, 255, 123, 200),
  'Relaxed': Color.fromARGB(255, 119, 206, 223),
  'Excited': Color.fromARGB(255, 206, 174, 255),
};

final feeling = [
  'Happy',
  'Angry!',
  'Tired',
  'Frustrated',
  'Awful',
  'In love',
  'Relaxed',
  'Excited',
];

Map<String, Color> areaColors = {
  'Work': const Color.fromARGB(200, 33, 149, 243),
  'Home': Color.fromARGB(185, 65, 224, 70),
  'Love': Color.fromARGB(205, 249, 149, 222),
  'Car': Color.fromARGB(184, 255, 76, 76),
  'Leisure': Color.fromARGB(170, 184, 31, 211)
};

Map<String, List<String>> caminosOptimos = {
  'Happy_Excited': ['Happy', 'Excited'],
  'Angry!_Excited': ['Angry!', 'Excited'],
  'Tired_Exited': ['Tired', 'Relaxed', 'In love', 'Happy', 'Excited'],
  'Frustrated_Excited': ['Frustrated', 'Excited'],
  'Awful_Excited': ['Awful', 'Angry!', 'Excited'],
  'In love_Excited': ['In love', 'Happy', 'Excited'],
  'Relaxed_Excited': ['Relaxed', 'In love', 'Happy', 'Excited'],
  'Excited_Excited': ['Excited'],
  'Happy_Happy': ['Happy'],
  'Angry!_Happy': ['Angry!', 'Excited', 'Happy'],
  'Tired_Happy': ['Tired', 'Relaxed', 'In love', 'Happy'],
  'Frustrated_Happy': ['Frustrated', 'Tired', 'Relaxed', 'In love', 'Happy'],
  'Awful_Happy': ['Awful', 'Angry!', 'Excited', 'Happy'],
  'In love_Happy': ['In love', 'Happy'],
  'Relaxed_Happy': ['Relaxed', 'In love', 'Happy'],
  'Excited_Happy': ['Excited', 'Happy'],
  'In love_In love': ['In love'],
  'Angry!_In love': ['Angry!', 'Excited', 'Happy', 'In love'],
  'Tired_In love': ['Tired', 'Relaxed', 'In love'],
  'Frustrated_In love': ['Frustrated', 'Tired', 'Relaxed', 'In love'],
  'Awful_In love': ['Awful', 'Excited', 'Happy', 'In love'],
  'Happy_In love': ['Happy', 'In love'],
  'Relaxed_In love': ['Relaxed', 'In love'],
  'Excited_In love': ['Excited', 'Happy', 'In love'],
  'Relaxed_Relaxed': ['Relaxed'],
  'Angry!_Relaxed': ['Angry!', 'Excited', 'Happy', 'Relaxed'],
  'Tired_Relaxed': ['Tired', 'Relaxed'],
  'Frustrated_Relaxed': ['Frustrated', 'Tired', 'Relaxed'],
  'Awful_Relaxed': ['Awful', 'Excited', 'Happy', 'Relaxed'],
  'In love_Relaxed': ['In love', 'Relaxed'],
  'Happy_Relaxed': ['Happy', 'In love', 'Relaxed'],
  'Excited_Relaxed': ['Excited', 'Happy', 'Relaxed'],
  'Happy_Tired': ['Happy', 'Relaxed', 'Tired'],
  'Angry!_Tired': ['Angry!', 'Frustrated', 'Awful', 'Tired'],
  'Frustrated_Tired': ['Frustrated', 'Tired'],
  'Awful_Tired': ['Awful', 'Tired'],
  'Tired_Tired': ['Tired'],
  'In love_Tired': ['In love', 'Relaxed', 'Tired'],
  'Relaxed_Tired': ['Relaxed', 'Tired'],
  'Excited_Tired': ['Excited', 'Happy', 'Relaxed', 'Tired'],
  'Happy_Awful': ['Happy', 'Relaxed', 'Tired', 'Awful'],
  'Angry!_Awful': ['Angry!', 'Frustrated', 'Awful'],
  'Tired_Awful': ['Tired', 'Awful'],
  'Frustrated_Awful': ['Frustrated', 'Awful'],
  'Awful_Awful': ['Awful'],
  'In love_Awful': ['In love', 'Relaxed', 'Tired', 'Awful'],
  'Relaxed_Awful': ['Relaxed', 'Tired', 'Awful'],
  'Excited_Awful': ['Excited', 'Happy', 'Relaxed', 'Tired', 'Awful'],
  'Happy_Frustrated': ['Happy', 'Relaxed', 'Tired', 'Frustrated'],
  'Angry!_Frustrated': ['Angry!', 'Frustrated'],
  'Tired_Frustrated': ['Tired', 'Frustrated'],
  'Frustrated_Frustrated': ['Frustrated'],
  'Awful_Frustrated': ['Awful', 'Frustrated'],
  'In love_Frustrated': ['In love', 'Relaxed', 'Tired', 'Frustrated'],
  'Relaxed_Frustrated': ['Relaxed', 'Tired', 'Frustrated'],
  'Excited_Frustrated': ['Excited', 'Frustrated'],
  'Happy_Angry!': ['Happy', 'Excited', 'Angry!'],
  'Angry!_Angry!': ['Angry!'],
  'Tired_Angry!': ['Tired', 'Frustrated', 'Angry!'],
  'Frustrated_Angry!': ['Frustrated', 'Angry!'],
  'Awful_Angry!': ['Awful', 'Frustrated', 'Angry!'],
  'In love_Angry!': ['In love', 'Happy', 'Excited', 'Angry!'],
  'Relaxed_Angry!': ['Relaxed', 'Happy', 'Excited', 'Angry!'],
  'Excited_Angry!': ['Excited', 'Angry!'],
};

List<String> camino = [];
Map<String, List<double>> musicVariables = {
  'target_tempo': List<double>.filled(10, 0),
  'target_energy': List<double>.filled(10, 0),
  'target_valence': List<double>.filled(10, 0),
  'target_danceability': List<double>.filled(10, 0),
  'target_loudness': List<double>.filled(10, 0),
};
